### ISSUE TITLE
Issue while downloading Closure_util through npm

### ISSUE THREAD

**Issue by raviindrapandey** [openlayers/closure-util#336]
Getting below error While Downloading closure through OpenLayers 

25876 verbose stack Error: closure-util@1.20.0 postinstall: `node ./bin/closure-util.js update`
25876 verbose stack Exit status 1
25876 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
25876 verbose stack     at emitTwo (events.js:106:13)
25876 verbose stack     at EventEmitter.emit (events.js:191:7)
25876 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
25876 verbose stack     at emitTwo (events.js:106:13)
25876 verbose stack     at ChildProcess.emit (events.js:191:7)
25876 verbose stack     at maybeClose (internal/child_process.js:886:16)
25876 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
25877 verbose pkgid closure-util@1.20.0
25878 verbose cwd D:\Work\OL4BuildKit\openlayers
25879 error Windows_NT 10.0.10586
25880 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "closure-util"
25881 error node v6.10.3
25882 error npm  v3.10.10
25883 error code ELIFECYCLE
25884 error closure-util@1.20.0 postinstall: `node ./bin/closure-util.js update`
25884 error Exit status 1
25885 error Failed at the closure-util@1.20.0 postinstall script 'node ./bin/closure-util.js update'.
25885 error Make sure you have the latest version of node.js and npm installed.
25885 error If you do, this is most likely a problem with the closure-util package,
25885 error not with npm itself.
25885 error Tell the author that this fails on your system:
25885 error     node ./bin/closure-util.js update
25885 error You can get information on how to open an issue for this project with:
25885 error     npm bugs closure-util
25885 error Or if that isn't available, you can get their info via:
25885 error     npm owner ls closure-util
25885 error There is likely additional logging output above.
25886 verbose exit [ 1, true ]

**Comment by HeavenlyHost** [comment]
This is getting silly, when is this going to be resolved, our coorporate proxy does not allow downloads github, this needs a fix as we are getting the same issue and have been for some time, when can we expect a fix ???

**Comment by BasieP** [comment]
with him ^^
We are having trouble on and off for this issue. Half the time we try building we get errors

**Comment by FredrikGeers** [comment]
closure-util 1.18.0 is functioning fine, all newer versions are failing
I'm seeing the following error in the install logs:
```
ERR! closure-util Could not find the End of Central Directory Record
```

**Comment by fredj** [comment]
We have a customer behind a corporate proxy which have a similar issue.
Using a `http` url for `compiler_url` (instead of `https`) fix the issue.

**Comment by fredj** [comment]
Maybe fixed with #380 , add a comment if it's not the case

**Comment by BasieP** [comment]
doesn't fix my issue. This due to the download containing .exe files, not because of a protocol issue..

**Comment by fredj** [comment]
Do you have the same issue when you run:
```
npm install google-closure-compiler
```
or:
```
npm install google-closure-library
```

**Comment by fredj** [comment]
There's nothing that we can do if you corporate proxy blocks exe download, try to open an issue at [closure-library](https://github.com/google/closure-library/issues) to ask them to remove the exe from the npm package.
